# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-rpi-base"
BBFILE_PATTERN_meta-rpi-base = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-rpi-base = "6"

LAYERSERIES_COMPAT_meta-rpi-base = "scarthgap"
